{"levelname": "ERROR", "asctime": "2017-10-09 18:22:10,825", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 22, in generate\n    print content.data\nAttributeError: 'Response' object has no attribute 'data'\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 22, in generate\n    print content.data\nAttributeError: 'Response' object has no attribute 'data'"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:23:31,267", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 22, in generate\n    print content._content['id']\nTypeError: string indices must be integers, not str\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 22, in generate\n    print content._content['id']\nTypeError: string indices must be integers, not str"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:29:55,703", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 33, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: u'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 33, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: u'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:30:30,912", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 33, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 33, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:30:32,735", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 33, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 33, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:33:14,420", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 34, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 34, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:33:32,515", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 34, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 34, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:34:46,399", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 35, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 37, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 35, in generate_idcard\n    qrcode =  generate_qrcode(paramObject.qrCode)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 20, in generate_qrcode\n    with open(path + test + '.png', 'w') as fstream:\nIOError: [Errno 2] No such file or directory: 'static/idCard/qrcodes/https://goo.gl/CjPBQJ.png'"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:51:54,216", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 34, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 82, in generate_idcard\n    return upload_to_s3(\"\", path+file_name)\n  File \"/home/arun/test/project/base_project/src/common/libraries/helper.py\", line 23, in upload_to_s3\n    os.remove(path=path+filename)\nTypeError: remove() takes no keyword arguments\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 34, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 82, in generate_idcard\n    return upload_to_s3(\"\", path+file_name)\n  File \"/home/arun/test/project/base_project/src/common/libraries/helper.py\", line 23, in upload_to_s3\n    os.remove(path=path+filename)\nTypeError: remove() takes no keyword arguments"}
{"levelname": "ERROR", "asctime": "2017-10-09 18:52:34,087", "message": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 34, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 82, in generate_idcard\n    return upload_to_s3(\"\", path+file_name)\n  File \"/home/arun/test/project/base_project/src/common/libraries/helper.py\", line 24, in upload_to_s3\n    os.remove(path=filename)\nTypeError: remove() takes no keyword arguments\n", "exc_info": "Traceback (most recent call last):\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/views.py\", line 486, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/arun/test/project/test_env/local/lib/python2.7/site-packages/rest_framework/decorators.py\", line 52, in handler\n    return func(*args, **kwargs)\n  File \"/home/arun/test/project/base_project/src/idcard/views/generateidcard.py\", line 34, in generate\n    img = generate_idcard(params, id)\n  File \"/home/arun/test/project/base_project/src/idcard/libraries/idcardlib.py\", line 82, in generate_idcard\n    return upload_to_s3(\"\", path+file_name)\n  File \"/home/arun/test/project/base_project/src/common/libraries/helper.py\", line 24, in upload_to_s3\n    os.remove(path=filename)\nTypeError: remove() takes no keyword arguments"}
